version: "3.7"

services:
  angular:
    container_name: angular
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "8088:80"
  prerender:
    image: bgadrian/docker-prerender
    container_name: prerender
    ports:
      - "3000:3000"
